export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST'
export const ARTICLE_LIST_FAILED = 'ARTICLE_LIST_FAILED'
export const ARTICLE_LIST_SUCCESSFULLY = 'ARTICLE_LIST_SUCCESSFULLY'

export const ARTICLE_SLIDESHOW_REQUEST = 'ARTICLE_SLIDESHOW_REQUEST'
export const ARTICLE_SLIDESHOW_FAILED = 'ARTICLE_SLIDESHOW_FAILED'
export const ARTICLE_SLIDESHOW_SUCCESSFULLY = 'ARTICLE_SLIDESHOW_SUCCESSFULLY'
