export const ARTICLE_SLIDESHOW_REQUEST = 'ARTICLE_SLIDESHOW_REQUEST'
export const ARTICLE_SLIDESHOW_FAILED = 'ARTICLE_SLIDESHOW_FAILED'
export const ARTICLE_SLIDESHOW_SUCCESSFULLY = 'ARTICLE_SLIDESHOW_SUCCESSFULLY'
